export type Villa = {
  id: string
  region: string
  name: string
  location: string
  beds: string
  size: string
  detail: string
  desc: string
  longDesc: string
  amenities: string[]
  images: string[]
}

export type RegionData = {
  title: string
  sub: string
  desc: string
  season: string
  villas: Villa[]
}

export const regions: Record<string, RegionData> = {
  'french-riviera': {
    title: 'French Riviera',
    sub: 'Côte d\'Azur',
    desc: 'From Cannes to Monaco, the Riviera offers our finest collection of clifftop estates and Belle Époque palaces overlooking the Mediterranean.',
    season: 'Peak season: June – September',
    villas: [
      {
        id: 'villa-les-pins',
        region: 'french-riviera',
        name: 'Villa Les Pins',
        location: 'Cap d\'Antibes',
        beds: '6 bedrooms',
        size: '850 m²',
        detail: '6 bedrooms · Private pool · Sea view',
        desc: 'A Belle Époque masterpiece hidden among umbrella pines on the Cap.',
        longDesc: "Villa Les Pins sits at the tip of Cap d'Antibes, surrounded by century-old pines and offering uninterrupted views across the Baie des Anges. The property blends original 1920s architecture with contemporary interiors — terrazzo floors, linen drapery, and gallery-quality art throughout. Six en-suite bedrooms, an 18-metre pool, private access to a rocky cove, and a full staff including chef and concierge.",
        amenities: ['18m pool', 'Private cove access', 'Full staff', 'Wine cellar', 'Cinema room', 'Tennis court', 'Chef', 'Security', 'Garage (4 cars)', 'Sea view'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'chateau-eze',
        region: 'french-riviera',
        name: 'Château Èze',
        location: 'Èze-sur-Mer',
        beds: '8 bedrooms',
        size: '1 200 m²',
        detail: '8 bedrooms · Panoramic terraces · Monaco views',
        desc: 'A perched hilltop château with views spanning the entire Riviera coast.',
        longDesc: "Perched 430 metres above sea level, Château Èze commands a 180-degree panorama from the Italian border to Cap Ferrat. The property — a converted medieval fortified house — has been meticulously restored with heated stone floors, vaulted ceilings and a wine cellar carved into the rock. Eight bedrooms, three salons, infinity pool and a helipad make it the most spectacular address on the Riviera.",
        amenities: ['Helipad', 'Infinity pool', 'Rock wine cellar', 'Panoramic terrace', 'Full staff', 'Private chef', 'Home cinema', 'Gym', 'Garage', 'Monaco views'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'villa-eden',
        region: 'french-riviera',
        name: 'Villa Eden',
        location: 'Saint-Jean-Cap-Ferrat',
        beds: '5 bedrooms',
        size: '620 m²',
        detail: '5 bedrooms · Private jetty · Direct sea access',
        desc: 'Modernist seafront villa with private jetty on the most prestigious peninsula.',
        longDesc: "Cap Ferrat is the most coveted peninsula in the world — and Villa Eden its finest modernist expression. Floor-to-ceiling glazing opens the entire south façade to the sea; a private jetty accommodates tenders up to 12 metres. Five bedrooms, each with en-suite marble bathroom. Interiors by a Parisian atelier. The garden descends in terraces to a natural swimming platform carved into the rock.",
        amenities: ['Private jetty', 'Rock swimming platform', 'Modernist architecture', 'Full glass south façade', 'Chef', 'Concierge', 'Pool', 'Garage', 'Sea access', 'Boat mooring'],
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
    ],
  },
  'monaco': {
    title: 'Monaco',
    sub: 'La Principauté',
    desc: 'The Principality\'s most exclusive residences — penthouses above the Grand Prix circuit and Belle Époque mansions on the Rock.',
    season: 'Year-round · Peak: May (Grand Prix)',
    villas: [
      {
        id: 'penthouse-casino',
        region: 'monaco',
        name: 'Penthouse Casino',
        location: 'Monte-Carlo',
        beds: '4 bedrooms',
        size: '480 m²',
        detail: '4 bedrooms · Rooftop terrace · Grand Prix views',
        desc: 'A triple-level penthouse directly above the Grand Prix circuit.',
        longDesc: "Positioned above the famous hairpin bend, this triple-level penthouse offers the ultimate Monaco Grand Prix experience — watch the cars from your private rooftop terrace with champagne in hand. Outside race week, it stands as one of the Principality's most coveted addresses: 480 square metres of Carrara marble, a home cinema, wine room and 360-degree terrace commanding views of the harbour and palace.",
        amenities: ['Grand Prix rooftop', 'Home cinema', 'Wine room', 'Marble throughout', '360° views', 'Concierge service', 'Garage (2 cars)', 'Smart home', 'Gym', 'Harbour views'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
      {
        id: 'villa-de-la-roche',
        region: 'monaco',
        name: 'Villa de la Roche',
        location: 'Monaco-Ville (The Rock)',
        beds: '6 bedrooms',
        size: '720 m²',
        detail: '6 bedrooms · Private garden · Palace district',
        desc: 'A restored Belle Époque mansion within the historic walls of the Rock.',
        longDesc: "One of fewer than thirty private residences within the ancient fortified walls of Monaco-Ville, Villa de la Roche is a rare privilege. Originally built in 1902 and fully restored in 2018, the property retains its original coffered ceilings and stone staircase while housing a contemporary kitchen, six en-suite bedrooms and a private garden — extraordinary for a territory where land is measured in square metres.",
        amenities: ['Historic walls location', 'Private garden', 'Original 1902 architecture', 'Contemporary interiors', 'Private garage', 'Staff quarters', 'Wine cellar', 'Fireplace', 'Security system', 'Palace district'],
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
    ],
  },
  'balearic-islands': {
    title: 'Balearic Islands',
    sub: 'Ibiza · Mallorca · Formentera',
    desc: 'White-washed fincas above Ibiza\'s calas, modernist estates on the Mallorcan coast, and barefoot retreats on pristine Formentera.',
    season: 'Peak season: June – September',
    villas: [
      {
        id: 'finca-sa-vinya',
        region: 'balearic-islands',
        name: 'Finca Sa Vinya',
        location: 'Santa Eulalia, Ibiza',
        beds: '7 bedrooms',
        size: '900 m²',
        detail: '7 bedrooms · Pool · Vineyard views',
        desc: 'An authentic Ibizan finca on 4 hectares of private vineyard, far from the crowds.',
        longDesc: "Finca Sa Vinya offers the authentic Ibiza that exists beyond the clubs — ancient olive trees, dry stone walls, and silence. The seven-bedroom property sits on 4 hectares of working vineyard producing its own Malvasia. Two pools, a clay tennis court, a summer kitchen under a pergola of wisteria, and a staff of six ensure every day unfolds at exactly the pace you choose.",
        amenities: ['Private vineyard (4ha)', 'Two pools', 'Tennis court', 'Summer kitchen', 'Staff of 6', 'Wine production', 'Olive grove', 'Mountain views', 'Heated pool', 'BBQ terrace'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'son-bennassar',
        region: 'balearic-islands',
        name: 'Son Bennassar',
        location: 'Deià, Mallorca',
        beds: '9 bedrooms',
        size: '1 100 m²',
        detail: '9 bedrooms · Infinity pool · Tramuntana mountains',
        desc: 'A UNESCO-listed mountain village estate with breathtaking Tramuntana views.',
        longDesc: "Deià is where Chopin composed, Robert Graves wrote, and artists have always retreated. Son Bennassar — a centuries-old mallorcan manor renovated by a Palma architect — sits above the village with an infinity pool facing the Tramuntana mountains and sea beyond. Nine bedrooms, a grand salon, chapel, wine cellar and 8 hectares of olive, lemon and orange groves.",
        amenities: ['UNESCO mountain village', '8ha estate', 'Infinity pool', 'Private chapel', 'Wine cellar', 'Olive groves', 'Panoramic terrace', 'Grand salon', 'Chef', 'Helipad'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
      {
        id: 'casa-formentera',
        region: 'balearic-islands',
        name: 'Casa Formentera',
        location: 'Es Caló, Formentera',
        beds: '4 bedrooms',
        size: '380 m²',
        detail: '4 bedrooms · Private beach · Pure barefoot luxury',
        desc: 'A minimalist white refuge steps from the most pristine beach in Europe.',
        longDesc: "Formentera remains the Mediterranean\'s best-kept secret — a car-free island where time moves differently. Casa Formentera is a whitewashed cube of pure minimalism: four bedrooms, an outdoor shower, a pool the colour of the sea beyond, and a private path to a 200-metre stretch of uninhabited beach. No neighbours. No noise. No compromise.",
        amenities: ['Private beach path', 'Pool', 'Outdoor shower', 'Minimalist design', 'Bicycle fleet', 'Kayaks', 'Snorkelling', 'Alfresco dining', 'Sea views', 'Cook on request'],
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
    ],
  },
  'greece': {
    title: 'Greece',
    sub: 'Mykonos · Santorini · Corfu',
    desc: 'Clifftop estates above the Caldera, whitewashed Cycladic retreats, and Ionian palazzos on emerald-green Corfu.',
    season: 'Peak season: June – September',
    villas: [
      {
        id: 'oia-estate',
        region: 'greece',
        name: 'Oia Estate',
        location: 'Oia, Santorini',
        beds: '5 bedrooms',
        size: '540 m²',
        detail: '5 bedrooms · Caldera views · Private cave pool',
        desc: 'A converted cave house perched above the Caldera with the world\'s finest sunset.',
        longDesc: "The Caldera view at Oia is one of the defining images of European travel — and Oia Estate puts you at its centre. A complex of three converted cave houses unified into a single five-bedroom property, it cascades down the volcanic cliff with a private cave pool carved into the rock face 300 metres above the sea. Breakfast arrives as the Aegean turns gold.",
        amenities: ['Caldera views', 'Cave pool', 'Sunset terrace', 'Private butler', 'Wine selection', 'Concierge', 'Chef on request', 'Sea views', 'Air conditioning', 'Jacuzzi'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
        ],
      },
      {
        id: 'villa-mykonos',
        region: 'greece',
        name: 'Villa Mykonos',
        location: 'Aleomandra, Mykonos',
        beds: '6 bedrooms',
        size: '700 m²',
        detail: '6 bedrooms · Infinity pool · Aegean panorama',
        desc: 'A Cycladic masterpiece with infinity pool overlooking the Aegean and Delos.',
        longDesc: "Positioned on a hillside overlooking the sacred island of Delos, Villa Mykonos embodies Cycladic architecture at its most refined. Brilliant white volumes, narrow corridors, and deep-set windows frame an Aegean of impossible blue. Six en-suite bedrooms, an infinity pool, an outdoor dining area seating twenty, and private transport to the island\'s finest beaches.",
        amenities: ['Infinity pool', 'Aegean panorama', 'Delos views', 'Outdoor dining (20)', 'Private driver', 'Chef', 'Daily maid', 'Sea kayaks', 'Snorkelling', 'Air conditioning'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'palazzo-corfu',
        region: 'greece',
        name: 'Palazzo Corfu',
        location: 'Paleokastritsa, Corfu',
        beds: '8 bedrooms',
        size: '950 m²',
        detail: '8 bedrooms · Private beach · Venetian architecture',
        desc: 'A restored Venetian palazzo above Corfu\'s most beautiful bay.',
        longDesc: "Corfu\'s Venetian heritage is unlike anywhere else in Greece — and Palazzo Corfu stands as its finest residential expression. Eight bedrooms spread across four floors of genuine 18th-century Venetian architecture, fully restored with contemporary comforts. The property commands a private bay with a natural shingle beach, boat house, and gardens of cypress, bougainvillea and old olive.",
        amenities: ['Private bay', 'Boat house', 'Venetian architecture', '18th century', 'Gardens', 'Private beach', 'Pool', 'Staff of 8', 'Chef', 'Wine cellar'],
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
    ],
  },
  'italy': {
    title: 'Italy',
    sub: 'Amalfi · Tuscany · Lake Como',
    desc: 'From a cliffside Amalfi estate to a Chianti vineyard and a lakeside villa on Como — Italy\'s greatest private addresses.',
    season: 'Peak season: May – October',
    villas: [
      {
        id: 'villa-positano',
        region: 'italy',
        name: 'Villa Positano',
        location: 'Positano, Amalfi Coast',
        beds: '5 bedrooms',
        size: '580 m²',
        detail: '5 bedrooms · Private boat mooring · Amalfi views',
        desc: 'A terraced clifftop villa above Positano\'s colourful harbour.',
        longDesc: "Villa Positano descends in four terraces from the cliff road to the sea, with private mooring for the villa\'s wooden gozzo. Each of the five bedrooms looks directly out over the Tyrrhenian Sea and the painted houses of Positano below. Breakfast is served on the highest terrace as the morning light finds the village; dinner on the sea-level terrace as the stars emerge.",
        amenities: ['Private boat mooring', 'Wooden gozzo boat', 'Four terraces', 'Sea views', 'Chef', 'Concierge', 'Pool', 'Jacuzzi', 'Daily housekeeping', 'Air conditioning'],
        images: [
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'tenuta-chianti',
        region: 'italy',
        name: 'Tenuta Chianti',
        location: 'Greve in Chianti, Tuscany',
        beds: '10 bedrooms',
        size: '1 400 m²',
        detail: '10 bedrooms · Working vineyard · Pool · Spa',
        desc: 'A 16th-century Tuscan estate at the heart of Chianti Classico country.',
        longDesc: "Tenuta Chianti is the definitive Tuscan experience: a 16th-century fortified farmhouse at the centre of a 28-hectare working Chianti Classico vineyard. Ten bedrooms in the main villa and two satellite cottages, a restored chapel, two pools, a spa, cookery school, and a cantina producing 80,000 bottles annually. Staff of twelve. Private sommelier. Absolute immersion in Tuscany.",
        amenities: ['28ha Chianti Classico estate', 'Cantina & winery', 'Cookery school', 'Spa', 'Two pools', 'Private chapel', 'Staff of 12', 'Sommelier', 'Olive oil production', 'Helipad'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'villa-como',
        region: 'italy',
        name: 'Villa Como',
        location: 'Bellagio, Lake Como',
        beds: '7 bedrooms',
        size: '820 m²',
        detail: '7 bedrooms · Private jetty · Belle Époque gardens',
        desc: 'A grand 1890s lakeside villa above Bellagio\'s famous promontory.',
        longDesc: "Lake Como has attracted the world\'s elite since Roman times — and Villa Como is its most distinguished private address. A late 19th-century neo-classical villa on a private promontory above Bellagio, with 3.5 hectares of Belle Époque gardens descending to a private jetty and boathouse. Seven bedrooms, grand reception rooms, and a heated pool set among the formal gardens.",
        amenities: ['Private jetty & boathouse', '3.5ha Belle Époque gardens', 'Heated pool', 'Neo-classical architecture', 'Motorboat', 'Chef', 'Gardener', 'Heated pool', 'Concierge', 'Mountain views'],
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
        ],
      },
    ],
  },
  'emirates': {
    title: 'Emirates',
    sub: 'Dubai · Abu Dhabi',
    desc: 'The finest private residences in the UAE — from Palm Jumeirah signature estates to desert retreats and Abu Dhabi island compounds.',
    season: 'Peak season: October – April',
    villas: [
      {
        id: 'palm-signature',
        region: 'emirates',
        name: 'Palm Signature',
        location: 'Palm Jumeirah, Dubai',
        beds: '8 bedrooms',
        size: '1 600 m²',
        detail: '8 bedrooms · Private beach · Infinity pool · Marina views',
        desc: 'The finest address on the Palm — a private beachfront compound with marina views.',
        longDesc: "Palm Signature occupies an entire frond tip on the Palm Jumeirah, offering 50 metres of private beach and unobstructed views across the Dubai Marina skyline. The 1,600 square metre compound houses eight bedrooms, a home cinema, spa, gymnasium, and a 25-metre infinity pool level with the Arabian Gulf. A private jetty accommodates a 15-metre vessel.",
        amenities: ['50m private beach', 'Private jetty', '25m infinity pool', 'Home cinema', 'Spa & gym', 'Smart home', 'Chef', 'Security team', 'Garage (6 cars)', 'Marina views'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
      {
        id: 'desert-retreat',
        region: 'emirates',
        name: 'Desert Retreat',
        location: 'Al Marmoom Desert, Dubai',
        beds: '6 bedrooms',
        size: '2 000 m²',
        detail: '6 bedrooms · 40ha desert estate · Private dune experience',
        desc: 'An extraordinary private desert estate 40 kilometres from the city — total seclusion.',
        longDesc: "Desert Retreat is an anomaly: a luxury estate within 40 hectares of private desert, 40 kilometres from Downtown Dubai. Six pavilion bedrooms connected by covered walkways, an open-air courtyard pool, a fire pit for desert evenings, and a falconry programme. Activities include private dune driving, camel rides, archery, and stargazing from a rooftop observatory. Staff of ten.",
        amenities: ['40ha private desert', 'Falconry programme', 'Dune driving', 'Rooftop observatory', 'Fire pit', 'Pool', 'Camel rides', 'Archery', 'Chef', 'Staff of 10'],
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
      {
        id: 'saadiyat-compound',
        region: 'emirates',
        name: 'Saadiyat Compound',
        location: 'Saadiyat Island, Abu Dhabi',
        beds: '10 bedrooms',
        size: '2 200 m²',
        detail: '10 bedrooms · Private island · Museum district',
        desc: 'A private island compound adjacent to the Louvre Abu Dhabi museum district.',
        longDesc: "Saadiyat Island is Abu Dhabi\'s cultural and residential jewel — home to the Louvre Abu Dhabi, the future Guggenheim, and the finest beach in the Gulf. The Compound occupies 6,000 square metres of private plot with a 120-metre beach frontage, three swimming pools, a tennis court and full sports facility. Ten bedrooms, staff quarters, and a private boat ramp.",
        amenities: ['120m beach frontage', '3 pools', 'Tennis court', 'Sports facility', 'Private boat ramp', 'Staff quarters', 'Chef', 'Security', 'Louvre proximity', 'Helipad'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
    ],
  },
  'caribbean': {
    title: 'Caribbean',
    sub: 'St. Barts · Mustique · Turks & Caicos',
    desc: 'The most exclusive islands in the Caribbean — St. Barts hillside estates, Mustique\'s private retreats, and Turks & Caicos beachfront compounds.',
    season: 'Peak season: December – April',
    villas: [
      {
        id: 'villa-stbarts',
        region: 'caribbean',
        name: 'Villa St. Barths',
        location: 'Gouverneur, St. Barthélemy',
        beds: '6 bedrooms',
        size: '750 m²',
        detail: '6 bedrooms · Infinity pool · Gouverneur Beach views',
        desc: "A clifftop estate above St. Barts' finest beach with a 270-degree ocean panorama.",
        longDesc: "St. Barthélemy is the island that defines Caribbean luxury — French, refined, and deliberately exclusive. Villa St. Barths sits above Gouverneur Beach on a private headland with 270 degrees of ocean view. Six bedrooms, an infinity pool cantilevered over the cliff face, a summer kitchen, and a fleet of electric Citroën Meyos for exploring the island. Chef, concierge and housekeeper included.",
        amenities: ['Cliff infinity pool', '270° ocean views', 'Gouverneur Beach access', 'Fleet of Meyos', 'Chef', 'Concierge', 'Housekeeper', 'Jacuzzi', 'Alfresco kitchen', 'Private heliport'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
        ],
      },
      {
        id: 'mustique-estate',
        region: 'caribbean',
        name: 'Mustique Estate',
        location: 'Mustique, St. Vincent',
        beds: '5 bedrooms',
        size: '620 m²',
        detail: '5 bedrooms · Caribbean Sea views · Full staff',
        desc: 'A rare private estate on the legendary island of Mustique — by invitation only.',
        longDesc: "Mustique is the most exclusive private island in the world — owned by a single company, visited by invitation only, and home to estates belonging to royalty and the world\'s most prominent families. Our Mustique Estate is a five-bedroom teak and coral-stone pavilion facing west across the Caribbean for sunsets that must be seen to be believed. Fully staffed, fully private.",
        amenities: ['Private island', 'West-facing sunsets', 'Full staff', 'Private pool', 'Tennis', 'Beach access', 'Golf cart', 'Chef', 'Butler', 'By invitation only'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
    ],
  },
  'collection': {
    title: 'Private Collection',
    sub: 'Extraordinary Residences Worldwide',
    desc: 'A curated selection of the world\'s most exceptional private residences — from Scottish castles to Japanese ryokans and Maldivian overwater compounds.',
    season: 'Year-round · Season varies by destination',
    villas: [
      {
        id: 'highland-castle',
        region: 'collection',
        name: 'Highland Castle',
        location: 'Perthshire, Scotland',
        beds: '12 bedrooms',
        size: '3 200 m²',
        detail: '12 bedrooms · 600 acres · Private salmon river',
        desc: 'A working Scottish castle with 600 acres of Highland estate and private salmon river.',
        longDesc: "Built in 1852 and in private ownership since, Highland Castle is a complete Highland experience: 600 acres of heather moorland, a private 4-kilometre stretch of the River Tay — one of Scotland\'s finest salmon rivers — and a working walled garden supplying the kitchen. Twelve bedrooms, a formal dining room seating 30, billiard room, whisky library, and full Highland sporting programme.",
        amenities: ['600 acres', 'Private salmon river (4km)', 'Walled garden', 'Whisky library', 'Dining room (30)', 'Billiard room', 'Highland sporting', 'Stalking', 'Chef', 'Full staff'],
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
      {
        id: 'maldives-compound',
        region: 'collection',
        name: 'Maldives Compound',
        location: 'North Malé Atoll, Maldives',
        beds: '6 bedrooms',
        size: '1 800 m²',
        detail: '6 overwater villas · Private island · Diving centre',
        desc: 'A private overwater compound on an uninhabited Maldivian island — utter isolation.',
        longDesc: "The Maldives Compound occupies an entire uninhabited island in the North Malé Atoll — a 40-minute seaplane from Velana International Airport. Six overwater villas connected by private jetty house up to twelve guests in total seclusion. A private PADI diving centre, chef trained at three-Michelin restaurants, spa pavilion over the lagoon, and your own fleet of dhonis for island exploration.",
        amenities: ['Private island', 'Overwater villas', 'PADI dive centre', 'Seaplane transfer', 'Michelin-trained chef', 'Spa pavilion', 'Snorkelling reef', 'Dhoni fleet', 'Sunset bar', 'Full staff'],
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1400&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1400&q=80',
          'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80',
        ],
      },
    ],
  },
}

export function getRegion(region: string): RegionData | undefined {
  return regions[region]
}

export function getVilla(region: string, id: string): Villa | undefined {
  return regions[region]?.villas.find(v => v.id === id)
}
